### ISSUE TITLE
[Feature]分包加载

### ISSUE THREAD

**Issue by parallel-kevin** [iException/anka#1]
现在的anka注册页面是直接注册在pages字段下，希望能够增加对分包加载的支持😁

**Comment by joe223** [comment]
0.2.0 已支持，用法

```shell
anka page test --scope=package2
```
则会在 `/pages/package2/test/` 下创建页面所需四个文件 `test.json` `test.js` `text.wxml` `test.wxss`，并在 app.json 中注册
