### ISSUE TITLE
一直 Launching...

### ISSUE THREAD

**Issue by xxyuze** [iException/anka#42]
- 初始化代码后，使用 anka dev 命令就一直卡在 Launching...

![image](https://user-images.githubusercontent.com/17399581/55337494-63286300-54d1-11e9-90eb-785fdc2567d9.png)

**Comment by joe223** [comment]
是windows平台嘛？顺便提供一下NodeJS和系统版本哇

**Comment by joe223** [comment]
@xxyuze Windows平台目前还没进行功能测试，不知是否有兴趣哇？

**Comment by xxyuze** [comment]
是 windows  
node v10.13.0
win10 专业版 1809

@joe223  该怎样测试？

**Comment by xxyuze** [comment]
在mac上尝试也是一样
卡在 Launching...
文件已经生成，但是缺少app.js

**Comment by joe223** [comment]
@xxyuze 推测可能是 https://github.com/iException/anka/blob/4e3a7105f5c4e4baa1ede817609a683c62ca0c81/src/core/class/Compiler.ts#L137 这个环节出现了问题。目前我身边缺少Windows设备，可能得清明假期才能找机会测试了

**Comment by joe223** [comment]
@xxyuze 跑anka的项目是什么样的呀？

**Comment by xxyuze** [comment]
- 全部是cli创建的，只改了appid


 - 在windows上，dist 里只有 npm_modules
 - 在mac上，dist 里缺少app.js、defaultData.js
 - 两个都卡在 Launching...

![image](https://user-images.githubusercontent.com/17399581/55528583-f5965580-56cf-11e9-80bd-7c95d5a66b33.png)

**Comment by joe223** [comment]
我晚上回去检查下，可能是文件权限的问题😂




| |
贺
|
|
邮箱：heyin223@163.com
|

签名由 网易邮箱大师 定制

在2019年04月04日 11:54，Yuze 写道：

全部是cli创建的，只改了appid

在windows上，dist 里只有 npm_modules

在mac上，dist 里缺少app.js、defaultData.js

两个都卡在 Launching...

**Comment by xxyuze** [comment]
试了下1.1.3 ，在windows和mac上还是同样的结果

**Comment by joe223** [comment]
@xxyuze  windows上的问题有点多，我还没搞完...

**Comment by joe223** [comment]
@xxyuze 搞好了老铁

@anka-dev/cli  1.2.0
